// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauSimplon;

#nullable disable

namespace RestauSimplon.Migrations
{
    [DbContext(typeof(RestauDbContext))]
    partial class RestauDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RestauSimplon.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommandeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prix")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("CommandeId");

                    b.ToTable("Article", (string)null);
                });

            modelBuilder.Entity("RestauSimplon.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorie", (string)null);
                });

            modelBuilder.Entity("RestauSimplon.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Phone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("RestauSimplon.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Commande", (string)null);
                });

            modelBuilder.Entity("RestauSimplon.CommandeArticle", b =>
                {
                    b.Property<int>("CommandeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommandeId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("CommandeArticle", (string)null);
                });

            modelBuilder.Entity("RestauSimplon.Article", b =>
                {
                    b.HasOne("RestauSimplon.Categorie", "Categorie")
                        .WithMany("Articles")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauSimplon.Commande", null)
                        .WithMany("Articles")
                        .HasForeignKey("CommandeId");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("RestauSimplon.Commande", b =>
                {
                    b.HasOne("RestauSimplon.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("RestauSimplon.CommandeArticle", b =>
                {
                    b.HasOne("RestauSimplon.Article", "Article")
                        .WithMany("CommandeArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauSimplon.Commande", "Commande")
                        .WithMany("CommandeArticles")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("RestauSimplon.Article", b =>
                {
                    b.Navigation("CommandeArticles");
                });

            modelBuilder.Entity("RestauSimplon.Categorie", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("RestauSimplon.Client", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("RestauSimplon.Commande", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("CommandeArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
