@RestauSimplon_HostAddress = https://localhost:7273


GET {{RestauSimplon_HostAddress}}/articles

###

@id=0
GET {{RestauSimplon_HostAddress}}/articles/{{id}}

###

POST {{RestauSimplon_HostAddress}}/articles
Content-Type: application/json

{
  
}

###


